default_language_version:
  python: python3
files: |
  (?x)^(
    src|
    tests
  )/.*\.py$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        files: ".*"
      - id: check-case-conflict
        files: ".*"
      - id: check-merge-conflict
        files: ".*"
      - id: check-yaml
        files: ".*"
      - id: end-of-file-fixer
        files: ".*"
        types: ["yaml"]
      - id: check-toml
        files: ".*"
        types: ["toml"]
      - id: debug-statements
        files: '^src/.*\.py$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "attrs"
          - "types-pyyaml"
          - "types-psutil"
        args:
          - "--no-warn-return-any" # Disable this because it doesn't know about 3rd party imports
          - "--ignore-missing-imports"
          - "--show-traceback"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.273
    hooks:
      - id: ruff
        args: [--no-cache]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]